Repository esmero/archipelago-deployment, pull requests merged in 2020-01, with the labels that each got.

#23 ISSUE:19 First Pass on deployment for 8.8.1 and Archipelago 8.x-1.0-beta2
  composer.json
  composer.lock
  docker-compose-nginx.yml
  docker-compose.yml
  persistent/solrconfig/conf/schema.xml
  persistent/solrconfig/conf/schema_extra_fields.xml
  persistent/solrconfig/conf/schema_extra_types.xml
  persistent/solrconfig/conf/solrconfig.xml
  persistent/solrconfig/conf/solrconfig_extra.xml
  persistent/solrconfig/conf/solrcore.properties
  web/.htaccess
  web/sites/default/default.settings.php
  web/sites/example.settings.local.php
  web/web.config
Labels: documentation, enhancement

#24 Fix Webprofiler BlockDataCollector
  composer.json
  patches/devel-webprofiler-BlocksDataCollector-3106747-2-D8.patch
Labels: bug, enhancement

#26 ISSUE-19d: Fix Config Warning on Display Field Copy Module 1.2
  composer.json
  config/sync/core.entity_view_display.node.digital_object.digital_object_with_pannellum_panorama.yml
  config/sync/core.entity_view_mode.node.digital_object_with_pannellum_panorama.yml
  patches/1.x-display_field_copy-missing-schema-3107615-2-D8.patch
Labels: bug, enhancement

#29 ISSUE-28: Updating the default Descriptive Metadata webform
  config/sync/webform.webform.descriptive_metadata.yml
Labels: enhancement

#31 ISSUE-19g: bump PHP upload size via nginx
  nginxconfigford8/default.conf
Labels: enhancement
